[functions.passkey-register-options]
enabled = true
verify_jwt = false
entrypoint = "./functions/passkey-register-options/index.ts"

[functions.passkey-register-verify]
enabled = true
verify_jwt = false
entrypoint = "./functions/passkey-register-verify/index.ts"

[functions.passkey-login-options]
enabled = true
verify_jwt = false
entrypoint = "./functions/passkey-login-options/index.ts"

[functions.passkey-login-verify]
enabled = true
verify_jwt = false
entrypoint = "./functions/passkey-login-verify/index.ts"
